# -*- coding: utf-8 -*-
"""Stemming_bengali.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15LXb4vYaox9aapo7hYseyUoeDh8gllcz
"""

pip install bangla-stemmer

from bangla_stemmer.stemmer import stemmer
def normalize_bengali(text):
  stmr = stemmer.BanglaStemmer()
  words= text.split()
  stems = [ ]
  for word in words:
    stm = stmr.stem(word)
    stems.append(stm)
  return " ".join(stems)

normalize_bengali("আন্দোলনের ফলে তিনটি প্রাণহানি এবং বহু লোক আহত হয়েছে। তবে আন্দোলনকারীরা উন্মুক্ত পদ্ধতিতে কয়লা খনি থেকে আহরণ বন্ধ করতে সক্ষম হয়েছিল")